import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import { Application } from '@splinetool/runtime';
import { SiNextdotjs, SiPython, SiTypescript, SiJavascript, SiJava, SiSqlite, SiMongodb, SiFacepunch } from "react-icons/si";
import { FaGithub, FaInstagram, FaTwitter, FaLinkedin, FaYoutube, FaKaggle } from "react-icons/fa";


export default function Home() {
  return (
    <>
      <Head>
        <title>Malcolm Wimbley</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/face_down_upside_icon_227319.ico" />
      </Head>

      
        <nav class="bg-tranparent border-gray-200 px-2 sm:px-4 py-2.5 rounded ">
          <div class="container flex flex-wrap items-center justify-between mx-auto">
            <a href="#" class="flex items-center">
            <SiFacepunch style={{color: 'rgb(79 70 229)'}} className='mr-3' size={30}/>
                <span class="self-center text-xl font-semibold whitespace-nowrap dark:text-white">Malcolm</span>
            </a>
            <div class="flex md:order-2">
              <button type="button" class="bg-transparent hover:duration-300 hover:bg-indigo-500 text-indigo-700 font-semibold hover:text-white py-2 px-4 border border-indigo-500 hover:border-transparent rounded-2xl">Resume</button>
              <button data-collapse-toggle="navbar-sticky" type="button" class="inline-flex items-center p-2 text-sm text-gray-500 rounded-lg md:hidden hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-gray-200 dark:text-gray-400 dark:hover:bg-gray-700 dark:focus:ring-gray-600" aria-controls="navbar-sticky" aria-expanded="false">
                <span class="sr-only">Open main menu</span>
                <svg class="w-6 h-6" aria-hidden="true" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M3 5a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 10a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 15a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1z" clip-rule="evenodd"></path></svg>
              </button>
            </div>
            <div class="hidden w-full md:block md:w-auto" id="navbar-default">
              <ul class="flex flex-col p-4 mt-4 bg-tranparent md:flex-row md:space-x-8 md:mt-0 md:text-sm md:font-medium border-1 ">
                <li>
                  <a href="#" class="block py-2 pl-3 pr-4 text-gray-700 rounded hover:duration-300 hover:bg-gray-100 md:hover:bg-transparent md:border-0 md:hover:text-blue-700 md:p-0 dark:text-gray-400 md:dark:hover:text-white dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent">Home</a>
                </li>
                <li>
                  <a href="#" class="block py-2 pl-3 pr-4 text-gray-700 rounded hover:duration-300 hover:bg-gray-100 md:hover:bg-transparent md:border-0 md:hover:text-blue-700 md:p-0 dark:text-gray-400 md:dark:hover:text-white dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent">About</a>
                </li>
                <li>
                  <a href="#" class="block py-2 pl-3 pr-4 text-gray-700 rounded hover:duration-300 hover:bg-gray-100 md:hover:bg-transparent md:border-0 md:hover:text-blue-700 md:p-0 dark:text-gray-400 md:dark:hover:text-white dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent">Services</a>
                </li>
                <li>
                  <a href="#" class="block py-2 pl-3 pr-4 text-gray-700 rounded hover:duration-300 hover:bg-gray-100 md:hover:bg-transparent md:border-0 md:hover:text-blue-700 md:p-0 dark:text-gray-400 md:dark:hover:text-white dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent">Pricing</a>
                </li>
                <li>
                  
                  <a href="#" class="block py-2 pl-3 pr-4 text-gray-700 rounded hover:duration-300 hover:bg-gray-100 md:hover:bg-transparent md:border-0 md:hover:text-blue-700 md:p-0 dark:text-gray-400 md:dark:hover:text-white dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent">Contact</a>
                </li>
              </ul>
              
            </div>
          </div>
        </nav>

        <div className='stickOne'>
          <a href='http://www.github.com'><FaGithub /></a>
          <a href='http://www.instagram.com'><FaInstagram /></a>
          <a href='http://www.github.com'><FaTwitter /></a>
          <a href='http://www.github.com'><FaLinkedin /></a>
          <a href='http://www.github.com'><FaYoutube /></a>
          <a href='http://www.github.com'><FaKaggle/></a>
        </div>

        <div className='stickTwo'>
          <a href='mailto:malcolmwimbley@gmail.com'>malcolmwimbley@gmail.com</a>
        </div>



        <main>
          <div className="hidden sm:mb-8 sm:flex sm:justify-center">
                  <div className="relative overflow-hidden rounded-xl py-1.5 px-4 text-sm font-semibold leading-6 ring-1 ring-white hover:duration-300 hover:bg-white hover:ring-gray-400">
                    <span className="text-gray-600">
                      Blog: Backtesting S&P500 With Python.{' '}
                      <a href="#" className="font-semibold text-indigo-600">
                        <span className="absolute inset-0" aria-hidden="true" />
                        Read more <span aria-hidden="true">&rarr;</span>
                      </a>
                    </span>
                  </div>
                </div>

          <h1 class='text-8xl text-center bold'>Malcolm Wimbley.</h1>
          <h2 class='font-semibold text-4xl text-center text-gray-700'>Full-Stack And Database Engineer.</h2>
          <div className='hidden w-full md:block'>

          <h3 className='font-semibold text-lg text-center max-w-lg mx-auto my-5 text-indigo-900'>
          ultrices sagittis orci a scelerisque purus semper eget duis at tellus at urna condimentum mattis pellentesque id nibh tortor id aliquet lectus proin nibh nisl condimentum id venenatis a condimentum
          </h3>
          <div className='icon'>
            <SiJavascript className='icons' size={30} style={{color: '#30364f'}} />
            <SiTypescript className='icons' size={30} style={{color: '#7b87ba'}}/>
            <SiNextdotjs className='icons' size={30} style={{color: '#a5add1'}}/>
            <SiPython className='icons' size={30} style={{color: '#e4e6f0'}}/>
            <SiJava className='icons' size={30} style={{color: '#a5add1'}}/>
            <SiSqlite className='icons' size={30} style={{color: '#7b87ba'}}/>
            <SiMongodb className='icons' size={30} style={{color: '#30364f'}}/>
          </div>
          </div>
        </main>
    

      
    </>
  )
}
